In [11]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')

In [12]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [13]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [14]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [15]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [16]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [17]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [19]:
# create a column age_group
labels=['Young adult','Adult','Middle_aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [20]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle_aged
1   19  Young adult
2   50  Middle_aged
3   21  Young adult
4   45  Middle_aged
5   46  Middle_aged
6   63       Senior
7   27  Young adult
8   26  Young adult
9   57  Middle_aged

In [21]:
# purchase_freq_days column

frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quaterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [22]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                      NaN              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                      NaN              Quarterly

In [23]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [24]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [25]:
df=df.drop('promo_code_used',axis=1)

In [26]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [27]:
from google.colab import files
df.to_csv('cleaned_data.csv', index=False)
files.download('cleaned_data.csv')

In [28]:
import sqlite3
import pandas as pd

# Create/connect to a database
conn = sqlite3.connect("mydb.db")

In [29]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('project.db')
df.to_sql('customers', conn, if_exists='replace', index=False)

print("Ready!")

Ready!

In [30]:
result = pd.read_sql('''
    SELECT Gender, SUM(purchase_amount) AS Revenue
    FROM customers
    GROUP BY Gender
''', conn)
result.to_csv('q1_gender.csv', index=False)
print(result)

   gender  Revenue
0  Female    75191
1    Male   157890

In [31]:
# which cust used discount but still spent more than avg purchase amount
result = pd.read_sql('''
    SELECT "Customer_id", "purchase_Amount"
    FROM customers
    WHERE "discount_applied" = 'Yes'
    AND "purchase_amount" >= (
        SELECT AVG("purchase_amount") FROM customers
    )
''', conn)
result.to_csv('q2_cust_more_than_avg.csv', index=False)
print(result)

     customer_id  purchase_amount
0              2               64
1              3               73
2              4               90
3              7               85
4              9               97
..           ...              ...
834         1667               64
835         1671               73
836         1673               73
837         1674               62
838         1676               90

[839 rows x 2 columns]

In [32]:
# Q3 - Top 5 products by avg review rating
result = pd.read_sql('''
    SELECT item_purchased,
           ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS avg_review_rating
    FROM customers
    GROUP BY item_purchased
    ORDER BY avg_review_rating DESC
    LIMIT 5
''', conn)
result.to_csv('q3_top_rated_products.csv', index=False)
print(result)

  item_purchased  avg_review_rating
0         Gloves               3.86
1        Sandals               3.84
2          Boots               3.82
3            Hat               3.80
4        T-shirt               3.78

In [33]:
# Q4 - Avg purchase amount by shipping type
result = pd.read_sql('''
    SELECT shipping_type,
           ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
    FROM customers
    WHERE shipping_type IN ('Standard', 'Express')
    GROUP BY shipping_type
''', conn)
result.to_csv('q4_shipping_avg.csv', index=False)
print(result)

  shipping_type  avg_purchase_amount
0       Express                60.48
1      Standard                58.46

In [34]:
# Q5 - Subscriber vs non-subscriber spend
result = pd.read_sql('''
    SELECT subscription_status,
           COUNT(customer_id) AS total_customers,
           ROUND(AVG(purchase_amount), 2) AS avg_spend,
           ROUND(SUM(purchase_amount), 2) AS total_revenue
    FROM customers
    GROUP BY subscription_status
    ORDER BY total_revenue DESC
''', conn)
result.to_csv('q5_subscriber_spend.csv', index=False)
print(result)

  subscription_status  total_customers  avg_spend  total_revenue
0                  No             2847      59.87       170436.0
1                 Yes             1053      59.49        62645.0

In [35]:
# Q6 - Top 5 products by discount rate
result = pd.read_sql('''
    SELECT item_purchased,
           ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_rate
    FROM customers
    GROUP BY item_purchased
    ORDER BY discount_rate DESC
    LIMIT 5
''', conn)
result.to_csv('q6_discount_rate.csv', index=False)
print(result)

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [36]:
# Q7 - Customer segmentation
result = pd.read_sql('''
    WITH customer_type AS (
        SELECT customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
        FROM customers
    )
    SELECT customer_segment,
           COUNT(*) AS number_of_customers
    FROM customer_type
    GROUP BY customer_segment
    ORDER BY number_of_customers DESC
''', conn)
result.to_csv('q7_customer_segments.csv', index=False)
print(result)

  customer_segment  number_of_customers
0            Loyal                 3116
1        Returning                  701
2              New                   83

In [37]:
# Q8 - Top 3 products per category
result = pd.read_sql('''
    WITH item_counts AS (
        SELECT category,
               item_purchased,
               COUNT(customer_id) AS total_orders,
               ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
        FROM customers
        GROUP BY category, item_purchased
    )
    SELECT item_rank, category, item_purchased, total_orders
    FROM item_counts
    WHERE item_rank <= 3
    ORDER BY category, item_rank
''', conn)
result.to_csv('q8_top_products_per_category.csv', index=False)
print(result)

    item_rank     category item_purchased  total_orders
0           1  Accessories        Jewelry           171
1           2  Accessories     Sunglasses           161
2           3  Accessories           Belt           161
3           1     Clothing          Pants           171
4           2     Clothing         Blouse           171
5           3     Clothing          Shirt           169
6           1     Footwear        Sandals           160
7           2     Footwear          Shoes           150
8           3     Footwear       Sneakers           145
9           1    Outerwear         Jacket           163
10          2    Outerwear           Coat           161

In [38]:
# Q9 - Repeat buyers subscription likelihood
result = pd.read_sql('''
    SELECT subscription_status,
           COUNT(customer_id) AS repeat_buyers
    FROM customers
    WHERE previous_purchases > 5
    GROUP BY subscription_status
    ORDER BY repeat_buyers DESC
''', conn)
result.to_csv('q9_repeat_buyers.csv', index=False)
print(result)

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            958

In [39]:
# Q10 - Revenue by age group
result = pd.read_sql('''
    SELECT age_group,
           ROUND(SUM(purchase_amount), 2) AS total_revenue
    FROM customers
    GROUP BY age_group
    ORDER BY total_revenue DESC
''', conn)
result.to_csv('q10_revenue_by_age_group.csv', index=False)
print(result)

     age_group  total_revenue
0  Young adult        62143.0
1  Middle_aged        59197.0
2        Adult        55978.0
3       Senior        55763.0